version: "3.8"

services:
  fizika:
    init: true
    image: schmelczera/fizika
    networks:
      - network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.8"
          memory: 512M
        reservations:
          cpus: "0.2"
          memory: 256M
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
        monitor: 10s
      restart_policy:
        condition: on-failure
        window: 30s
    volumes:
      - /shared/fizika:/var/lib/mysql

networks:
  network:
